name: Uda'CityShop [latest tag] - Package with Docker
on:
  push:
    branches: [ main , master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend service
        uses: docker/build-push-action@v2
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asheshanr/frontend:latest
          
      - name: Build and push productcatalogservice service
        uses: docker/build-push-action@v2
        with:
          context: ./src/productcatalogservice
          file: ./src/productcatalogservice/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asheshanr/productcatalogservice:latest
      
      - name: Build and push currencyservice service
        uses: docker/build-push-action@v2
        with:
          context: ./src/currencyservice
          file: ./src/currencyservice/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asheshanr/currencyservice:latest
      
      - name: Build and push adservice service
        uses: docker/build-push-action@v2
        with:
          context: ./src/adservice
          file: ./src/adservice/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asheshanr/adservice:latest
